services:
  osrm:
    image: ghcr.io/project-osrm/osrm-backend:v6.0.0
    container_name: osrm-berlin
    ports:
      - "5000:5000"
    volumes:
      - ./data:/data
    command: osrm-routed --algorithm mld /data/berlin-latest.osrm
    restart: unless-stopped
